name: issue-closed

on:
  issues:
    types:
      - closed
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number'
        required: true

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Report
        id: report
        uses: piyoppi/actions-labeled-duration@2bb298f805444e6b243ba88ddfdc11ac47fd64ee
        with:
          labels: label1,label2,ラベルA
          project_columns: TODO,Doing
          issue_comment: '⌛このIssueの作業にかかった時間は以下の通りです'
          issue_number: ${{ github.event.inputs.issue_number }}
      - name: echo
        shell: bash
        env:
          OUTPUTTED_CONTENT: ${{ steps.report.outputs.labeled_duration_details }}
        run: printf %q $OUTPUTTED_CONTENT
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: issue-tracked
      - name: write
        shell: bash
        env:
          OUTPUTTED_CONTENT: ${{ steps.report.outputs.labeled_duration_details }}
        run: |
          git config --global user.email "bot@garakuta-toolbox.com"
          git config --global user.name "piyoppi-bot"
          branch='issue-tracked'
          dir='./issue-tracked'
          if [ ! -d $dir ]; then
            mkdir $dir
          fi
          echo $OUTPUTTED_CONTENT > "$dir/${{ github.event.issue.number }}.json"
          git add .
          git commit -m "add / replace ${{ github.event.issue.number }}.json"
          git push origin $branch
